apiVersion: v1
kind: Service
metadata:
  name: hotels-service
spec:
  type: NodePort  # Здесь меняем на NodePort
  selector:
    app: hotels-service
  ports:
    - protocol: TCP
      port: 9064  # Порт внутри кластера
      targetPort: 9064  # Порт контейнера
      nodePort: 30064  # Порт, который будет доступен на хосте